# Screen settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

# Player settings
PLAYER_SPEED = 5
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32
PLAYER_COLOR = (255, 0, 0)
MAX_JUMPS = 2
MAX_STAMINA = 800
MIN_STAMINA = 450
STAMINA_DRAIN_RATE = 2
STAMINA_RECOVERY_RATE = 15

# Directions
LEFT = "left"
RIGHT = "right"

# Asset dimensions
TILE_SIZE = 16
GROUND_LEVEL = 100
PLAYER_SPAWN = 100
